"""followers

Revision ID: 359242680c2d
Revises: 41626effb0bd
Create Date: 2019-12-19 21:05:38.055672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359242680c2d'
down_revision = '41626effb0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
