"""new fields in user model

Revision ID: 41626effb0bd
Revises: 3be4bf7db580
Create Date: 2019-12-17 10:57:50.104499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41626effb0bd'
down_revision = '3be4bf7db580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
